config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [ :index, :new, :create, :show ] do
    resources :words, only: [ :new, :create, :show ]
  end

  root 'users#index'

  get '/words/:word' => 'words#show_all'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :words
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  COMMON_WORDS = %w{
    the of and a to in is you that it he was for on are as with his they I at be
    this have from or one had by word but not what all were we when your can
    said there use an each which she do how their if will up other about out
    many then them these so some her would make like him into time has look two
    more write go see number no way could people my than first water been call
    who oil its now find long down day did get come made may part
  }

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    @words = Word.pluck(:word).uniq.sort
  end

  def show
    set_defined_word_hash
    set_frequencies
    @words = @user.words.sort_by { |word| word.word }
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if !ValidateHundredWordLength.new(description).call
      @user.errors[:description] = "You must use exactly 100 words to describe yourself. No more. No less."
      render :new
    elsif !@user.save
      @user.errors[:db] = "Didn't work. Not sure why."
      render :new
    else
      redirect_to @user, notice: "User was successfully created."
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :description)
  end

  def description
    user_params[:description]
  end

  def defined_word_models
    @user.words.where(word: @user.description.split.map { |word| SimplifiedWord.new(word).call })
  end

  def set_defined_word_hash
    @defined_word_hash = defined_word_models.inject({}) do |hash, word_model|
      hash[word_model.word] = word_model
      hash
    end
    @defined_word_hash.default = nil
  end

  def set_frequencies
    descriptions = User.pluck(:description)
    words = descriptions.join(" ").split.map { |word| SimplifiedWord.new(word).call }
    words -= common_words
    words -= @user.name.split.map { |word| SimplifiedWord.new(word).call }
    @frequencies = words.inject({}) do |frequencies, word|
      count = words.count { |w| w == word }
      frequencies[word] = count if count > 1
      frequencies
    end
    @frequencies.default = 0
  end

  def common_words
    COMMON_WORDS
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  COMMON_WORDS = %w{
    the of and a to in is you that it he was for on are as with his they I at be
    this have from or one had by word but not what all were we when your can
    said there use an each which she do how their if will up other about out
    many then them these so some her would make like him into time has look two
    more write go see number no way could people my than first water been call
    who oil its now find long down day did get come made may part
  }

  def new
    set_user
    @word = @user.words.new
    @word.word = word_params[:new_word]
  end

  def create
    set_user
    build_word
    if ValidateHundredWordLength.new(definition).call && @word.save
      redirect_to user_word_url(@user, @word)
    else
      render :new
    end
  end

  def show
    set_user
    set_word
    set_defined_word_hash
    set_frequencies(@word.word)
  end

  def show_all
    @word = params[:word]
    set_definitions(@word)
    set_frequencies(@word)
  end

  private

  def build_word
    @word = @user.words.build(word_params[:word])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_word
    @word = @user.words.find(params[:id])
  end

  def word_params
    params.permit(:new_word, :user_id, word: [ :word, :definition ])
  end

  def definition
    params[:word][:definition]
  end

  def defined_word_models
    @user.words.where(word: @word.definition.split.map { |word| SimplifiedWord.new(word).call })
  end

  def set_defined_word_hash
    @defined_word_hash = defined_word_models.inject({}) do |hash, word_model|
      hash[word_model.word] = word_model
      hash
    end
    @defined_word_hash.default = nil
  end

  def set_frequencies(word)
    definitions = Word.where(word: word).pluck(:definition)
    words = definitions.join(" ").split.map { |word| SimplifiedWord.new(word).call }
    words -= common_words
    words.delete(word)
    @frequencies = words.inject({}) do |frequencies, word|
      count = words.count { |w| w == word }
      frequencies[word] = count if count > 1
      frequencies
    end
    @frequencies.default = 0
  end

  def common_words
    COMMON_WORDS
  end

  def set_definitions(word)
    @definitions = Word.where(word: word).map do |word|
      { author: word.user.name, text: word.definition }
    end
    @definitions.shuffle!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cleanup(word)
    simplify(word)
  end

  def simplify(word)
    SimplifiedWord.new(word).call
  end

  def colour_decile(word, frequencies)
    decile = deciles(frequencies)[simplify(word)]
    "decile#{decile}"
  end

  def deciles(frequencies)
    max_frequency = frequencies.values.max
    deciles = frequencies.keys.inject({}) do |deciles, word|
      deciles[word] = (frequencies[word] * 10.0 / max_frequency).ceil
      deciles
    end
    deciles.default = 1
    deciles
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dictionary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, cols: 60, rows: 10, onkeyup: "updateWordCount()", onchange: "updateWordCount()" %>
    <div id="word_count">0/100</div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dictionary</h1>

<p><strong>Words:</strong></p>
<ul>
<% if @words.count { |word| !('a'..'z').include?(word.chars.first.downcase) } > 0 %>
  <li><strong>#:</strong>
  <% @words.select { |word| !('a'..'z').include?(word.chars.first.downcase) }.each do |word| %>
    <a href="/words/<%= word.html_safe %>"><%= word %></a>
  <% end %>
  </li>
<% end %>
<% ('a'..'z').each do |letter| %>
  <% if @words.count { |word| word.chars.first.downcase == letter } > 0 %>
    <li><strong><%= letter.upcase %>:</strong>
    <% @words.select { |word| word.chars.first.downcase == letter }.each do |word| %>
      <a href="/words/<%= word.html_safe %>"><%= word %></a>
    <% end %>
    </li>
  <% end %>
<% end %>
</ul>

<p><strong>Users:</strong>
<% @users.each do |user| %>
  <%= link_to user.name, user %><%= "," unless user == @users.last %>
<% end %>
</p>

<p><%= link_to 'New User', new_user_path %></p>

<p><a href="mailto:matt.heard@powershop.co.nz">Make a suggestion or report a bug</a></p>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.name %></h1>

<p><strong>has defined the words:</strong>
<% @words.each do |word| %>
  <span><%= link_to word.word, [@user, word] %></span>
<% end %>
</p>

<p>
  <strong>Who is <%= @user.name %>?</strong>
  <% @user.description.split.each do |word| %>
    <% if @defined_word_hash[simplify(word)] %>
      <%= link_to word, [@user, @defined_word_hash[simplify(word)]], class: "frequency #{colour_decile(word, @frequencies)}" %>
    <% else %>
      <%= link_to word, new_user_word_path(@user, new_word: simplify(word)), class: "frequency #{colour_decile(word, @frequencies)}" %>
    <% end %>
  <% end %>
</p>

<%= link_to 'Back', users_path %>

app/views/words/new.html.erb
<h1>What does '<%= @word.word %>' mean?</h1>

<%= form_for([ @user, @word ]) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_field :word, value: @word.word, hidden: true %>
  </div>
  <div class="field">
    <%= f.label :definition %><br>
    <%= f.text_area :definition, cols: 60, rows: 10, onkeyup: "updateWordCount()", onchange: "updateWordCount()" %>
    <div id="word_count">0/100</div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', user_path(@user) %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @word.word %></h1>
<p>as defined by <strong><%= @user.name %></strong></p>

<p>
  <% @word.definition.split.each do |word| %>
    <% if @defined_word_hash[cleanup(word)] %>
      <%= link_to word, [@user, @defined_word_hash[cleanup(word)]], class: "frequency #{colour_decile(word, @frequencies)}" %>
    <% else %>
      <%= link_to word, new_user_word_path(@user, new_word: cleanup(word)), class: "frequency #{colour_decile(word, @frequencies)}" %>
    <% end %>
  <% end %>
</p>

<%= link_to 'Back', user_path(@user) %>

app/views/words/show_all.html.erb
<h1><%= @word %></h1>

<% if @definitions.empty? %>
  <p>It looks like nobody has defined this word yet.</p>
<% end %>

<% @definitions.each do |definition| %>
  <p>as defined by <strong><%= definition[:author] %></strong></p>
  <p>
  <% definition[:text].split.each do |word| %>
    <%= link_to word, "/words/#{simplify(word)}", class: "frequency #{colour_decile(word, @frequencies)}" %>
  <% end %>
  </p>
  <br />
<% end %>

<%= link_to 'Back', users_path %>